### PR TITLE
Add documentation to Num instances.

### PR DESCRIPTION
**Pull request by Profpatsch**
#43

### CODE REVIEW

**Comment by Profpatsch** [comment]
This should fix the warnings and document the Semiring case.

**Comment by Profpatsch** [comment]
Okay, it seems the new GHC changed some import strategies, Travis says this doesn’t build.

**Comment by Gabriel439** [comment]
It's because those imports are necessary for older versions of `ghc` (pre-7.10)

**Comment by Gabriel439** [comment]
Thanks!

**Pull request merged**
