### PR TITLE
Update tutorial to use `stack script`

### PR DESCRIPTION
**Pull request by menelaos**

### CODE REVIEW

**Comment by menelaos** [comment]
Travis failed due to exceeding the time limit.

**Comment by Gabriel439** [comment]
Does the header still need the `--package turtle` part?

**Comment by menelaos** [comment]
I believe it doesn't. 
As part of [#2805](https://github.com/commercialhaskell/stack/issues/2805), an experimental import parser, which works quite well, was implemented in [29df0c4](https://github.com/commercialhaskell/stack/commit/29df0c44d8323eab737072c2d8e8e329b70ddf42).
Unfortunately, the current `stack script` documentation does not yet mention this feature.
The relevant parts were written on February 9, 2017 ([4984a5a](https://github.com/commercialhaskell/stack/commit/4984a5aaae83fecb5d293fcd710af89212459097)), i.e. about one week before the parser came into existence.

**Comment by Gabriel439** [comment]
Oh, neat!  Thanks for doing this and I learned something new :)

**Pull request merged**
