### PR TITLE
add 'eprintf' to faciliate printing to stderr

### PR DESCRIPTION
**Pull request by lynnard**

### CODE REVIEW

**Comment by Gabriel439** [comment]
Thank you for adding this!

**Comment by PierreR** [comment]
Is it really a good idea to use such short name ? Why not errPrintf ? 
The protolude is using putErrText for instance.

**Comment by Gabriel439** [comment]
@PierreR: I thought `eprintf` was the idiomatic name that people usually used for `printf` to `stderr`

**Comment by PierreR** [comment]
If it is let's be it ;-)

**Pull request merged**
