### PR TITLE
Refactor to use outhandle

### PR DESCRIPTION
**Pull request by int-index**
I've noticed some code duplication and removed it.

### CODE REVIEW

**Comment by Gabriel439** [comment]
Note that this will conflict with #191 .  However, perhaps we should upstream the `ignoreSIGPIPE` fix into `outhandle`

**Comment by int-index** [comment]
I'll just rebase this branch once #191 is merged.

**Comment by maoe** [comment]
Please feel free to merge this first. It looks fine as-is, whereas my PR needs more commit. I can rebase my branch when this PR is merged.

**Comment by int-index** [comment]
Ok, I'll merge it then.

**Pull request merged**
